= System Requirement Specification OpenFastTrace AsciiDoc Plugin
:toc:         left
:toclevels:   3
:stylesheet:  oft_spec.css

== Introduction

link:https://github.com/itsallcode/openfasttrace[OpenFastTrace] (OFT) is a requirement tracing suite written in Java.
The AsciiDoc Plugin provides support for reading OFT _specification items_ from Asciidoctor files.

=== Goals

The plugin's goal is to allow developers to use the popular link:https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc markup language] for writing link:https://github.com/itsallcode/openfasttrace/blob/main/doc/user_guide.md#specification-item[OFT specification items].

=== Terms and Abbreviations

The following list gives you an overview of terms and abbreviations commonly used in OFT documents.

* Artifact: a container for specification items
* Artifact type: the role of an artifact in a specification hierarchy
* Coverage: Specification items covering other specification items
* Coverage provider: a specification item that provides coverage
* Coverage requester: a specification item that needs coverage
* OFT: OpenFastTrace (this project)
* Specification item: holds either a requirement or coverage
* Specification artifact: a data source containing specification items (e.g. file, ticket system,
    database)

== Features

[.specitem, oft-sid="feat~asciidoc-import~1", oft-needs="req"]
=== AsciiDoc Import

The plugin imports specification items from AsciiDoc files.

.Rationale
[.rationale]
--
* AsciiDoc is a lightweight and semantic markup language primarily designed for writing technical documentation.
* The language can be used to produce a variety of presentation-rich output formats, all from content encoded in a concise, human-readable, plain text format.

For those reasons AsciiDoc is a suitable candidate for writing specification that can be read and maintained over a long time.
--

== Functional Requirements

Markdown is a simple ASCII-based markup format that is designed to be human readable in the source. While it can be rendered into HTML, it is perfectly eye-friendly even before rendering.

Markdown focuses on content over formatting by giving the document structure like headlines, paragraphs and lists. The combination of being lightweight, human-readable and structure-oriented makes it a good fit for writing specifications as code.

OFT defines a Markdown format that we call "Requirement-Enhanced Markdown" which is a superset of the regular Markdown. Any Markdown renderer can render this format without understanding it. The additional structural definitions tell OFT which part of the text is a specification item.

For backward compatibility OFT supports a variant of this format that was introduced at Elektrobit. This format is a little bit closer to ReqM2, the predecessor that sparked the OFT idea. We recommend using standard OFT Markdown format in new documents though since this format is cleaner.

[.specitem, oft-sid="req~asciidoc-file-extensions~1", oft-needs="dsn", oft-covers="feat~asciidoc-import~1"]
=== Supported File Extensions

The plugin supports reading AsciiDoc files having the standard `.adoc` extension.

[.specitem, oft-sid="req~asciidoc-standard-syntax~1", oft-needs="dsn", oft-covers="feat~asciidoc-import~1"]
=== AsciiDoc Standard Syntax

The OFT AsciiDoc specification artifact format uses the standard AsciiDoc syntax without proprietary extensions.

.Rationale
[.rationale]
The specification documents that the OFT AsciiDoc importer reads must be viewable with any regular AsciiDoc reader and as plain text.

[.specitem, oft-sid="req~asciidoc-outline-readable~1", oft-needs="dsn", oft-covers="feat~asciidoc-import~1"]
=== Markdown Outline Readable

The AsciiDoc outline -- a table of contents created from the heading structure by various AsciiDoc editors -- must be human-readable.

.Rationale
[.rationale]
In long specification documents, the outline is the primary means of navigating the document. Only if the outline can be read easily, it is useful for authoring specification documents.

[.specitem, oft-sid="req~artifact-type-forwarding-in-asciidoc~1", oft-needs="dsn", oft-covers="feat~asciidoc-import~1"]
=== Artifact Type Forwarding in Markdown

The AsciiDoc format features a compact way to forward a requirement from the artifact type that was originally required to one or more different artifact types.

.Rationale
[.rationale]
Often a system requirement does not affect the high-level architecture. In this case it is convenient for the architect to hand it down to lower levels directly.
